#!/usr/bin/env bash

function usage {
  if [ -n "$1" ]
  then
    echo $1 1>&2
  fi
  cat 1>&2 << EOF
usage: copyf [filename]

Move file into all clipboards
EOF
  exit 1
}

if [ -z "$1" ]
then
  usage
fi

if [ ! -e "$1" ]
then
  usage "File not found"
fi

xclip -selection clipboard $1
xclip $1
